SECRET_KEY = ''
CLIENT_ID = ''
CLIENT_SECRET = ''
REDIRECT_URI = ''
USERNAME = ''
SPOTIFY_AUTH_URL = "https://accounts.spotify.com/authorize"
SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token"
SPOTIFY_API_BASE_URL = "https://api.spotify.com"
API_VERSION = "v1"
SPOTIFY_API_URL = "{}/{}".format(SPOTIFY_API_BASE_URL, API_VERSION)
PORT = 5009
SCOPE = 'playlist-modify-public playlist-modify-private user-top-read user-library-read user-read-private user-read-recently-played user-library-modify user-library-read user-read-private user-read-email user-follow-modify user-follow-read playlist-read-collaborative playlist-read-private'
ROOT_NAME = "root_app/"
TRACK_FEATURES_LIMIT = 50
ADD_TRACKS_LIMIT = 100
MINIMUM_TEMPO = 50
MAXIMUM_TEMPO = 205
STEP_TEMPO = 5
TOLERANCE_TEMPO = 4
EXPIRE = 3600
